// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvT_RW6GmTbVocwiYJPBzfCFoGuOrOM2Q',
    appId: '1:787622730324:web:9590ac753e74c033c5ebc1',
    messagingSenderId: '787622730324',
    projectId: 'mdunia-4de29',
    authDomain: 'mdunia-4de29.firebaseapp.com',
    storageBucket: 'mdunia-4de29.firebasestorage.app',
    measurementId: 'G-LJ4B3YMN3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiCs8kS5lAZ4HMJzw_kwpFhnsYnX39ynw',
    appId: '1:787622730324:android:88ca53bffdbd1d3fc5ebc1',
    messagingSenderId: '787622730324',
    projectId: 'mdunia-4de29',
    storageBucket: 'mdunia-4de29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWNDt_BvkTJzT-2nOSraSKnOoZ68AUduk',
    appId: '1:787622730324:ios:63e6982cba9fc0bcc5ebc1',
    messagingSenderId: '787622730324',
    projectId: 'mdunia-4de29',
    storageBucket: 'mdunia-4de29.firebasestorage.app',
    iosBundleId: 'com.example.madunia_admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWNDt_BvkTJzT-2nOSraSKnOoZ68AUduk',
    appId: '1:787622730324:ios:63e6982cba9fc0bcc5ebc1',
    messagingSenderId: '787622730324',
    projectId: 'mdunia-4de29',
    storageBucket: 'mdunia-4de29.firebasestorage.app',
    iosBundleId: 'com.example.madunia_admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvT_RW6GmTbVocwiYJPBzfCFoGuOrOM2Q',
    appId: '1:787622730324:web:7f9ec207fbac3ae4c5ebc1',
    messagingSenderId: '787622730324',
    projectId: 'mdunia-4de29',
    authDomain: 'mdunia-4de29.firebaseapp.com',
    storageBucket: 'mdunia-4de29.firebasestorage.app',
    measurementId: 'G-S1RHL2WED5',
  );
}
